/*
 * RysunekJPanel.java
 *
 * Created on April 22, 2008, 9:16 PM
 */

package fflames;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
/**
 *
 * @author  victories
 */
public class RysunekJPanel extends javax.swing.JPanel {
    private Image image;
    private Point2D.Double pointFrom = new Point2D.Double(0.0, 0.0);
    private Point2D.Double pointTo = new Point2D.Double(0.0, 0.0);
    private MouseEvent event;
      
    /** Creates new form RysunekJPanel */
    public RysunekJPanel() {
        initComponents();
    }

    public Point2D.Double getPointFrom() {
        return pointFrom;
    }

    public Point2D.Double getPointTo() {
        return pointTo;
    }
    
    public void resetPoints() {
        pointFrom.setLocation(0.0, 0.0);
        pointTo.setLocation(1.0, 1.0);
    }
    
    public void setImage(Image bI) {
        image = bI;
        repaint();   
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, 640, 480);
        
        g.drawImage(image, 0, 0, null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        Point2D.Double tempFrom = 
                new Point2D.Double(pointFrom.getX() + (event.getX()/640.0)*(pointTo.getX() - pointFrom.getX()),
                                   pointFrom.getY() + (event.getY()/480.0)*(pointTo.getY() - pointFrom.getY()));
        pointTo.setLocation(pointFrom.getX() + (evt.getX()/640.0)*(pointTo.getX()-pointFrom.getX()),
                            pointFrom.getY() + (evt.getY()/480.0)*(pointTo.getY()-pointFrom.getY()));
        pointFrom.setLocation(tempFrom.getX(), tempFrom.getY());
    }//GEN-LAST:event_formMouseReleased
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        event = evt;
    }//GEN-LAST:event_formMousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
