/*
 * PreviewJPanel.java
 *
 * Created on April 22, 2008, 9:16 PM
 */

package fflames.gui.forms;

import fflames.gui.model.RenderedImageModel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.geom.Point2D;
import java.beans.PropertyChangeEvent;

public class PreviewJPanel extends javax.swing.JPanel {
	
	private static final long serialVersionUID = 2552472331006455414L;
	private Image image;
	private Point2D.Double pointFrom = new Point2D.Double(0.0, 0.0);
	private Point2D.Double pointTo = new Point2D.Double(0.0, 0.0);
	private MouseEvent event;
	private RenderedImageModel _model;
	private final PropertyChangeListener _listener = new PropertyChangeListener();

	/** Creates new form PreviewJPanel */
	public PreviewJPanel() {
		initComponents();
	}

	public RenderedImageModel getModel() {
		return _model;
	}
	
	public void setModel(RenderedImageModel model) {
		if(_model != null) {
			_model.removePropertyChangeListener(_listener);
		}
		_model = model;
		_model.addPropertyChangeListener(_listener);
	}
	
	@Override
	public void paint(Graphics g) {
		super.paint(g);

		int currentWidth = getWidth();
		int currentHeight = getHeight();

		g.setColor(Color.BLACK);
		g.fillRect(0, 0, currentWidth, currentHeight);

		if (image != null) {
			Image scaledImage = image.getScaledInstance(currentWidth, currentHeight, Image.SCALE_SMOOTH);

			g.drawImage(scaledImage, 0, 0, null);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mousePressed(java.awt.event.MouseEvent evt) {
				formMousePressed(evt);
			}

			@Override
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				formMouseReleased(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 390,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 301,
				Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	private void formMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseReleased
		Point2D.Double tempFrom = new Point2D.Double(pointFrom.getX() + (event.getX() / 640.0)
				* (pointTo.getX() - pointFrom.getX()), pointFrom.getY() + (event.getY() / 480.0)
				* (pointTo.getY() - pointFrom.getY()));
		pointTo.setLocation(pointFrom.getX() + (evt.getX() / 640.0) * (pointTo.getX() - pointFrom.getX()),
				pointFrom.getY() + (evt.getY() / 480.0) * (pointTo.getY() - pointFrom.getY()));
		pointFrom.setLocation(tempFrom.getX(), tempFrom.getY());
	}// GEN-LAST:event_formMouseReleased

	private void formMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMousePressed
		event = evt;
	}// GEN-LAST:event_formMousePressed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables
	
	private class PropertyChangeListener implements java.beans.PropertyChangeListener {

		@Override
		public void propertyChange(PropertyChangeEvent evt) {
			switch (evt.getPropertyName()) {
				case RenderedImageModel.IMAGE:
					image = (Image) evt.getNewValue();
					repaint();
					break;
			}
		}

	}
}
