/*
 * VariationsEditor.java
 *
 * Created on March 18, 2008, 4:10 PM
 */
package fflames.gui.forms;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;

import fflames.gui.model.VariationsTableModel;

import javax.swing.BoxLayout;

/**
 *
 * @author victories
 */
public class VariationsEditor extends javax.swing.JPanel {

	private static final long serialVersionUID = 2305910609219372143L;
	private VariationsTableModel _model;

	/**
	 * Creates new form VariationsEditor
	 */
	public VariationsEditor() {
		_model = new VariationsTableModel();

		initComponents();

		ListSelectionModel lsm = _variationsJTable.getSelectionModel();
		lsm.addListSelectionListener(new VariationJTableListSelectionHandler());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		setLayout(new BoxLayout(this, BoxLayout.X_AXIS));

		_variationsTableJScrollPane = new javax.swing.JScrollPane();
		_variationsJTable = new javax.swing.JTable();

		_variationsJTable.setModel(_model);
		_variationsTableJScrollPane.setViewportView(_variationsJTable);
		add(_variationsTableJScrollPane);
	}// </editor-fold>//GEN-END:initComponents

	public VariationsTableModel getModel() {
		return _model;
	}

	public void setModel(VariationsTableModel model) {
		_variationsJTable.setModel(model);
	}
	
	private javax.swing.JTable _variationsJTable;
	private javax.swing.JScrollPane _variationsTableJScrollPane;

	// End of variables declaration//GEN-END:variables
	class VariationJTableListSelectionHandler implements ListSelectionListener {

		@Override
		public void valueChanged(ListSelectionEvent e) {
		}
	}
}
