/*
 * MyFractals.java
 *
 * Created on March 5, 2008, 9:43 PM
 */

package fflames.forms;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.lang.Double;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.*;
import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import org.xml.sax.*;
import org.xml.sax.helpers.*;

import fflames.Drawning;
import fflames.interfaces.IMainWindowController;
import fflames.interfaces.IVariation;
import fflames.model.Functions;
import fflames.model.Transform;
import fflames.model.VariationsFactory;

/**
 * 
 * @author victories
 */
public class MyFractals extends javax.swing.JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = -7603616574289128827L;

	/** Creates new form MyFractals */
	public MyFractals(IMainWindowController controller) {
		super();

		functions = new Functions();
		functions.addListDataListener(new FunctionsListener());

		_controller = controller;

		initComponents();

		listaFunkcji.getSelectionModel().addListSelectionListener(new ListaFunListSelectionHandler());

		bI = new BufferedImage(640, 480, BufferedImage.TYPE_INT_ARGB);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		fileChooser = new javax.swing.JFileChooser();
		bgrDrawning = new javax.swing.ButtonGroup();
		imageFileChooser = new javax.swing.JFileChooser();
		wybraneFunkcjeLabel = new javax.swing.JLabel();
		rysujButton = new javax.swing.JButton();
		usunButton = new javax.swing.JButton();
		dodajButton = new javax.swing.JButton();
		listaFunkcjiScrollPane = new javax.swing.JScrollPane();
		listaFunkcji = new javax.swing.JList();
		jTP = new javax.swing.JTabbedPane();
		opcjeJPanel = new javax.swing.JPanel();
		iloscIteracjiJLabel = new javax.swing.JLabel();
		iloscIteracjiJTextField = new javax.swing.JTextField();
		wielkoscObrJLabel = new javax.swing.JLabel();
		widthJTextField = new javax.swing.JTextField();
		xJLabel = new javax.swing.JLabel();
		hieghtJTextField = new javax.swing.JTextField();
		symetrieJLabel = new javax.swing.JLabel();
		rotationsQuantityJTF = new javax.swing.JTextField();
		jrbDrawFast = new javax.swing.JRadioButton();
		jrbDrawSlow = new javax.swing.JRadioButton();
		trAfJPanel = new javax.swing.JPanel();
		aLabel = new javax.swing.JLabel();
		wspATextField = new javax.swing.JTextField();
		dLabel = new javax.swing.JLabel();
		wspDTextField = new javax.swing.JTextField();
		bLabel = new javax.swing.JLabel();
		wspBTextField = new javax.swing.JTextField();
		cLabel = new javax.swing.JLabel();
		eLabel = new javax.swing.JLabel();
		wspETextField = new javax.swing.JTextField();
		fLabel = new javax.swing.JLabel();
		wspFTextField = new javax.swing.JTextField();
		wspCTextField = new javax.swing.JTextField();
		prLabel = new javax.swing.JLabel();
		wspPrTextField = new javax.swing.JTextField();
		losujTransJButton = new javax.swing.JButton();
		wariationsJPanel = new fflames.forms.WariationsJPanel();
		coloringJPanel = new fflames.forms.ColoringJPanel();
		infoJPanel = new javax.swing.JPanel();
		infoAutorJLabel = new javax.swing.JLabel();
		infoTytulJLabel = new javax.swing.JLabel();
		infoWersjaJLabel = new javax.swing.JLabel();
		infoDesc2JLabel = new javax.swing.JLabel();
		otworzDaneJButton = new javax.swing.JButton();
		zapiszDaneJButton = new javax.swing.JButton();
		rysunekJPanel = new fflames.forms.RysunekJPanel();
		rysujFragButton = new javax.swing.JButton();
		wskJProgressBar = new javax.swing.JProgressBar();
		saveImageButton = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();

		fileChooser.setApproveButtonText("Otw�rz");
		fileChooser.setCurrentDirectory(null);
		fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Pliki XML", "xml"));

		imageFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
		imageFileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Pliki png", "png"));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MyFractals");
		setMinimumSize(new java.awt.Dimension(800, 600));
		setName("mainFrame"); // NOI18N

		wybraneFunkcjeLabel.setText("Wybrane funkcje:");

		rysujButton.setText("Rysuj");
		rysujButton.setEnabled(false);
		rysujButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rysujButtonActionPerformed(evt);
			}
		});

		usunButton.setText("Usun");
		usunButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				usunButtonActionPerformed(evt);
			}
		});

		dodajButton.setText("Dodaj");
		dodajButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dodajButtonActionPerformed(evt);
			}
		});

		listaFunkcji.setModel(functions);
		listaFunkcji.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		listaFunkcjiScrollPane.setViewportView(listaFunkcji);

		iloscIteracjiJLabel.setText("Ilosc iteracji:");

		iloscIteracjiJTextField.setText("100000");

		wielkoscObrJLabel.setText("Wielko�� obrazka:");

		widthJTextField.setText("640");

		xJLabel.setText("x");

		hieghtJTextField.setText("480");

		symetrieJLabel.setText("Ilo�� obrot�w:");

		rotationsQuantityJTF.setText("0");

		bgrDrawning.add(jrbDrawFast);
		jrbDrawFast.setSelected(true);
		jrbDrawFast.setText("Rysuj szybko");

		bgrDrawning.add(jrbDrawSlow);
		jrbDrawSlow.setText("Rysuj dok�adnie");

		javax.swing.GroupLayout opcjeJPanelLayout = new javax.swing.GroupLayout(opcjeJPanel);
		opcjeJPanel.setLayout(opcjeJPanelLayout);
		opcjeJPanelLayout.setHorizontalGroup(opcjeJPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				opcjeJPanelLayout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								opcjeJPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												opcjeJPanelLayout
														.createSequentialGroup()
														.addComponent(iloscIteracjiJLabel)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(iloscIteracjiJTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE, 91,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												opcjeJPanelLayout
														.createSequentialGroup()
														.addComponent(wielkoscObrJLabel)
														.addGap(15, 15, 15)
														.addComponent(widthJTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE, 45,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(xJLabel)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(hieghtJTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE, 44,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												opcjeJPanelLayout
														.createSequentialGroup()
														.addComponent(symetrieJLabel)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(rotationsQuantityJTF,
																javax.swing.GroupLayout.PREFERRED_SIZE, 51,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
						.addGroup(
								opcjeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jrbDrawFast).addComponent(jrbDrawSlow))
						.addContainerGap(21, Short.MAX_VALUE)));

		opcjeJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { hieghtJTextField,
				widthJTextField });

		opcjeJPanelLayout.setVerticalGroup(opcjeJPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				opcjeJPanelLayout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								opcjeJPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(iloscIteracjiJLabel)
										.addComponent(iloscIteracjiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jrbDrawFast))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								opcjeJPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(wielkoscObrJLabel)
										.addComponent(hieghtJTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(xJLabel)
										.addComponent(widthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jrbDrawSlow))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								opcjeJPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(symetrieJLabel)
										.addComponent(rotationsQuantityJTF, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(57, 57, 57)));

		jTP.addTab("Opcje", opcjeJPanel);

		aLabel.setText("A");

		wspATextField.setText("0");

		dLabel.setText("D");

		wspDTextField.setText("0");

		bLabel.setText("B");

		wspBTextField.setText("0");

		cLabel.setText("C");

		eLabel.setText("E");

		wspETextField.setText("0");

		fLabel.setText("F");

		wspFTextField.setText("0");

		wspCTextField.setText("0");

		prLabel.setText("Pr.");

		wspPrTextField.setText("1");

		losujTransJButton.setText("Losuj");
		losujTransJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				losujTransJButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout trAfJPanelLayout = new javax.swing.GroupLayout(trAfJPanel);
		trAfJPanel.setLayout(trAfJPanelLayout);
		trAfJPanelLayout
				.setHorizontalGroup(trAfJPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								trAfJPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												trAfJPanelLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																trAfJPanelLayout
																		.createSequentialGroup()
																		.addGroup(
																				trAfJPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								trAfJPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												aLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												wspATextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								trAfJPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												dLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												wspDTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				trAfJPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								trAfJPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												bLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												wspBTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												cLabel))
																						.addGroup(
																								trAfJPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												eLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												wspETextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												fLabel)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				trAfJPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								wspFTextField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								60,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								trAfJPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												wspCTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												prLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												wspPrTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addComponent(losujTransJButton))
										.addContainerGap(108, Short.MAX_VALUE)));
		trAfJPanelLayout.setVerticalGroup(trAfJPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				trAfJPanelLayout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								trAfJPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(aLabel)
										.addComponent(wspATextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(bLabel)
										.addComponent(wspBTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(cLabel)
										.addComponent(wspCTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(prLabel)
										.addComponent(wspPrTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								trAfJPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(dLabel)
										.addComponent(eLabel)
										.addComponent(wspDTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(wspETextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(fLabel)
										.addComponent(wspFTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
						.addComponent(losujTransJButton).addContainerGap()));

		jTP.addTab("Transformacja afiniczna", trAfJPanel);
		jTP.addTab("Wariacje", wariationsJPanel);
		jTP.addTab("Kolorowanie", coloringJPanel);

		infoAutorJLabel.setText("Autor programu: Pawe� Korus (victories@tlen.pl), inf. in�. III r.");

		infoTytulJLabel.setText("Tytu� programu: MyFractals");

		infoWersjaJLabel.setText("Wersja: 1.0");

		infoDesc2JLabel.setText("Semestr letni, 2008.");

		javax.swing.GroupLayout infoJPanelLayout = new javax.swing.GroupLayout(infoJPanel);
		infoJPanel.setLayout(infoJPanelLayout);
		infoJPanelLayout.setHorizontalGroup(infoJPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				infoJPanelLayout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								infoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(infoAutorJLabel).addComponent(infoTytulJLabel)
										.addComponent(infoWersjaJLabel).addComponent(infoDesc2JLabel))
						.addContainerGap(108, Short.MAX_VALUE)));
		infoJPanelLayout.setVerticalGroup(infoJPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				infoJPanelLayout.createSequentialGroup().addGap(14, 14, 14).addComponent(infoTytulJLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(infoAutorJLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(infoWersjaJLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(infoDesc2JLabel).addContainerGap(52, Short.MAX_VALUE)));

		jTP.addTab("O programie", infoJPanel);

		otworzDaneJButton.setText("Otworz dane");
		otworzDaneJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				otworzDaneJButtonActionPerformed(evt);
			}
		});

		zapiszDaneJButton.setText("Zapisz dane");
		zapiszDaneJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				zapiszDaneJButtonActionPerformed(evt);
			}
		});

		rysunekJPanel.setMinimumSize(new java.awt.Dimension(640, 480));
		rysunekJPanel.setPreferredSize(new java.awt.Dimension(640, 480));
		rysunekJPanel.setLayout(new java.awt.FlowLayout());

		rysujFragButton.setText("Rysuj fragment");
		rysujFragButton.setEnabled(false);
		rysujFragButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rysujFragButtonActionPerformed(evt);
			}
		});

		wskJProgressBar.setStringPainted(true);

		saveImageButton.setText("Zapisz obrazek");
		saveImageButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveImageButtonActionPerformed(evt);
			}
		});

		btnCancel.setText("Anuluj");
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(jTP,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 425,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(wybraneFunkcjeLabel)
																				.addComponent(
																						listaFunkcjiScrollPane,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						381,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						dodajButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178, Short.MAX_VALUE)
																				.addComponent(
																						wskJProgressBar,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178, Short.MAX_VALUE)
																				.addComponent(
																						usunButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178, Short.MAX_VALUE)
																				.addComponent(
																						otworzDaneJButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178, Short.MAX_VALUE)
																				.addComponent(
																						zapiszDaneJButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178, Short.MAX_VALUE)
																				.addComponent(
																						rysujFragButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178, Short.MAX_VALUE)
																				.addComponent(
																						rysujButton,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178, Short.MAX_VALUE)
																				.addComponent(
																						saveImageButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178, Short.MAX_VALUE)
																				.addComponent(
																						btnCancel,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178, Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(rysunekJPanel,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 640,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout.createSequentialGroup()
														.addComponent(wybraneFunkcjeLabel)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(listaFunkcjiScrollPane,
																javax.swing.GroupLayout.DEFAULT_SIZE, 148,
																Short.MAX_VALUE))
										.addComponent(jTP, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(
												layout.createSequentialGroup()
														.addComponent(dodajButton)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(usunButton)
														.addGap(30, 30, 30)
														.addComponent(otworzDaneJButton)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(zapiszDaneJButton)
														.addGap(36, 36, 36)
														.addComponent(rysujButton)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(rysujFragButton)
														.addGap(34, 34, 34)
														.addComponent(saveImageButton)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(btnCancel)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(wskJProgressBar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(rysunekJPanel, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 469,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void rysujFragButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rysujFragButtonActionPerformed
		bI = new BufferedImage(Integer.parseInt(widthJTextField.getText()),
				Integer.parseInt(hieghtJTextField.getText()), BufferedImage.TYPE_INT_ARGB);

		functions.addRotations(Integer.parseInt(rotationsQuantityJTF.getText()));
		if (functions.checkPropabilities() == 1)
			JOptionPane.showInternalMessageDialog(this.getContentPane(), "Suma prawdopodobie�stw jest wi�ksza ni� 1!",
					"Uwaga", JOptionPane.WARNING_MESSAGE);

		int howToDraw = 2;
		if (jrbDrawSlow.isSelected())
			howToDraw = 1;

		drawning = new Drawning(functions, Integer.parseInt(iloscIteracjiJTextField.getText()),
				coloringJPanel.getColoring(), rysunekJPanel.getPointFrom(), rysunekJPanel.getPointTo(), bI, howToDraw);
		drawning.addPropertyChangeListener(new ProgressBarChange());
		drawning.execute();
	}// GEN-LAST:event_rysujFragButtonActionPerformed

	/**
	 * 
	 * @param evt
	 */
	private void otworzDaneJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_otworzDaneJButtonActionPerformed
		int returnValue = fileChooser.showOpenDialog(this);

		if (returnValue == JFileChooser.APPROVE_OPTION) {
			try {
				_controller.loadFractalFile(fileChooser.getSelectedFile(), functions);
				coloringJPanel.setFunctionsCount(functions.getFunctionsQuantity());
			} catch (IOException e) {
				JOptionPane.showMessageDialog(this, "Error when reading from choosen file", "File import error",
						JOptionPane.ERROR_MESSAGE);
			}
		}
	}// GEN-LAST:event_otworzDaneJButtonActionPerformed

	private void zapiszDaneJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_zapiszDaneJButtonActionPerformed
		OutputStream bout = null;
		OutputStreamWriter out = null;

		int returnValue = fileChooser.showSaveDialog(this);

		if (returnValue == JFileChooser.APPROVE_OPTION) {
			try {
				bout = new BufferedOutputStream(new FileOutputStream(fileChooser.getSelectedFile().getName()));
				out = new OutputStreamWriter(bout, "8859_2");

				out.write("<?xml version=\"1.0\" encoding=\"ISO-8859-2\"?>\r\r");
				out.write("<Fractal>\n");

				functions.writeXML(out);

				out.write("</Fractal>\r\n");
				out.flush();
				out.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}// GEN-LAST:event_zapiszDaneJButtonActionPerformed

	private void rysujButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rysujButtonActionPerformed
		functions.addRotations(Integer.parseInt(rotationsQuantityJTF.getText()));
		if (functions.checkPropabilities() == 1)
			JOptionPane.showInternalMessageDialog(this.getContentPane(), "Suma prawdopodobie�stw jest wi�ksza ni� 1!",
					"Uwaga", JOptionPane.WARNING_MESSAGE);

		rysunekJPanel.resetPoints();
		bI = new BufferedImage(Integer.parseInt(widthJTextField.getText()),
				Integer.parseInt(hieghtJTextField.getText()), BufferedImage.TYPE_INT_ARGB);

		int howToDraw = 2;
		if (jrbDrawSlow.isSelected())
			howToDraw = 1;

		drawning = new Drawning(functions, Integer.parseInt(iloscIteracjiJTextField.getText()),
				coloringJPanel.getColoring(), rysunekJPanel.getPointFrom(), rysunekJPanel.getPointTo(), bI, howToDraw);
		drawning.addPropertyChangeListener(new ProgressBarChange());
		drawning.execute();
	}// GEN-LAST:event_rysujButtonActionPerformed

	private void usunButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usunButtonActionPerformed
		try {
			((Functions) listaFunkcji.getModel()).removeElement(listaFunkcji.getSelectedIndex());
			coloringJPanel.setFunctionsCount(functions.getSize());

		} catch (Exception ex) {
		}
	}// GEN-LAST:event_usunButtonActionPerformed

	private void dodajButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dodajButtonActionPerformed
		try {
			functions.addElement(new Transform(new AffineTransform(new Double(wspATextField.getText()), new Double(
					wspDTextField.getText()), new Double(wspBTextField.getText()), new Double(wspETextField.getText()),
					new Double(wspCTextField.getText()), new Double(wspFTextField.getText())), wariationsJPanel
					.getWariations(), new Double(wspPrTextField.getText())));
			coloringJPanel.setFunctionsCount(functions.getFunctionsQuantity());
		} catch (Exception ex) {
			JOptionPane.showInternalMessageDialog(this.getContentPane(), ex.getMessage(), "Uwaga",
					JOptionPane.WARNING_MESSAGE);
		}
	}// GEN-LAST:event_dodajButtonActionPerformed

	private void losujTransJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_losujTransJButtonActionPerformed
		wspATextField.setText(String.valueOf(Math.random()).substring(0, 6));
		wspBTextField.setText(String.valueOf(Math.random()).substring(0, 6));
		wspCTextField.setText(String.valueOf(Math.random()).substring(0, 6));
		wspDTextField.setText(String.valueOf(Math.random()).substring(0, 6));
		wspETextField.setText(String.valueOf(Math.random()).substring(0, 6));
		wspFTextField.setText(String.valueOf(Math.random()).substring(0, 6));
	}// GEN-LAST:event_losujTransJButtonActionPerformed

	private void saveImageButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveImageButtonActionPerformed
		int returnValue = imageFileChooser.showSaveDialog(this);

		if (returnValue == JFileChooser.APPROVE_OPTION) {
			try {
				File file = imageFileChooser.getSelectedFile();

				ImageIO.write(bI, "png", file);
			} catch (IOException ex) {
				Logger.getLogger(MyFractals.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}// GEN-LAST:event_saveImageButtonActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelActionPerformed
		drawning.cancel(true);
	}// GEN-LAST:event_btnCancelActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel aLabel;
	private javax.swing.JLabel bLabel;
	private javax.swing.ButtonGroup bgrDrawning;
	private javax.swing.JButton btnCancel;
	private javax.swing.JLabel cLabel;
	private fflames.forms.ColoringJPanel coloringJPanel;
	private javax.swing.JLabel dLabel;
	private javax.swing.JButton dodajButton;
	private javax.swing.JLabel eLabel;
	private javax.swing.JLabel fLabel;
	private javax.swing.JFileChooser fileChooser;
	private javax.swing.JTextField hieghtJTextField;
	private javax.swing.JLabel iloscIteracjiJLabel;
	private javax.swing.JTextField iloscIteracjiJTextField;
	private javax.swing.JFileChooser imageFileChooser;
	private javax.swing.JLabel infoAutorJLabel;
	private javax.swing.JLabel infoDesc2JLabel;
	private javax.swing.JPanel infoJPanel;
	private javax.swing.JLabel infoTytulJLabel;
	private javax.swing.JLabel infoWersjaJLabel;
	private javax.swing.JTabbedPane jTP;
	private javax.swing.JRadioButton jrbDrawFast;
	private javax.swing.JRadioButton jrbDrawSlow;
	private javax.swing.JList listaFunkcji;
	private javax.swing.JScrollPane listaFunkcjiScrollPane;
	private javax.swing.JButton losujTransJButton;
	private javax.swing.JPanel opcjeJPanel;
	private javax.swing.JButton otworzDaneJButton;
	private javax.swing.JLabel prLabel;
	private javax.swing.JTextField rotationsQuantityJTF;
	private javax.swing.JButton rysujButton;
	private javax.swing.JButton rysujFragButton;
	private fflames.forms.RysunekJPanel rysunekJPanel;
	private javax.swing.JButton saveImageButton;
	private javax.swing.JLabel symetrieJLabel;
	private javax.swing.JPanel trAfJPanel;
	private javax.swing.JButton usunButton;
	private fflames.forms.WariationsJPanel wariationsJPanel;
	private javax.swing.JTextField widthJTextField;
	private javax.swing.JLabel wielkoscObrJLabel;
	private javax.swing.JProgressBar wskJProgressBar;
	private javax.swing.JTextField wspATextField;
	private javax.swing.JTextField wspBTextField;
	private javax.swing.JTextField wspCTextField;
	private javax.swing.JTextField wspDTextField;
	private javax.swing.JTextField wspETextField;
	private javax.swing.JTextField wspFTextField;
	private javax.swing.JTextField wspPrTextField;
	private javax.swing.JLabel wybraneFunkcjeLabel;
	private javax.swing.JLabel xJLabel;
	private javax.swing.JButton zapiszDaneJButton;
	// End of variables declaration//GEN-END:variables
	private Functions functions;
	private BufferedImage bI;
	private Drawning drawning;

	class ProgressBarChange implements PropertyChangeListener {
		public ProgressBarChange() {
		};

		public void propertyChange(PropertyChangeEvent evt) {
			if (evt.getPropertyName().compareTo("progress") == 0) {
				int progress = (Integer) evt.getNewValue();
				wskJProgressBar.setValue(progress);
			}
			if (((SwingWorker) evt.getSource()).isDone() == true) {
				rysunekJPanel.setImage(bI.getScaledInstance(640, 480, Image.SCALE_FAST));
			}
		}
	}

	class FunctionsListener implements ListDataListener {

		public void intervalAdded(ListDataEvent e) {
			throw new UnsupportedOperationException("Not supported yet.");
		}

		public void intervalRemoved(ListDataEvent e) {
			throw new UnsupportedOperationException("Not supported yet.");
		}

		public void contentsChanged(ListDataEvent e) {
			rysujButton.setEnabled(!(functions.getSize() == 0));
			rysujFragButton.setEnabled(!(functions.getSize() == 0));
		}

	}

	class ListaFunListSelectionHandler implements ListSelectionListener {

		public void valueChanged(ListSelectionEvent e) {
			double[] coefs = new double[6];
			functions.getTransformAt(listaFunkcji.getSelectedIndex()).getAffineTr().getMatrix(coefs);
			wspATextField.setText(String.valueOf(coefs[0]));
			wspBTextField.setText(String.valueOf(coefs[2]));
			wspCTextField.setText(String.valueOf(coefs[4]));
			wspDTextField.setText(String.valueOf(coefs[1]));
			wspETextField.setText(String.valueOf(coefs[3]));
			wspFTextField.setText(String.valueOf(coefs[5]));
			wspPrTextField.setText(functions.getPr(listaFunkcji.getSelectedIndex()).toString());
			wariationsJPanel.setWariations(functions.getTransformAt(listaFunkcji.getSelectedIndex()).getWariations());
		}

	}

	private IMainWindowController _controller;
}