/*
 * WariationsJPanel.java
 *
 * Created on March 18, 2008, 4:10 PM
 */

package fflames.forms;

import java.util.Vector;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;

import fflames.interfaces.IVariation;
import fflames.model.VariationsFactory;
import fflames.model.VariationsTableModel;
import javax.swing.BoxLayout;

/**
 * 
 * @author victories
 */
public class WariationsJPanel extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2305910609219372143L;

	/** Creates new form WariationsJPanel */
	public WariationsJPanel() {
		initComponents();

		ListSelectionModel lsm = wariationsJTable.getSelectionModel();
		lsm.addListSelectionListener(new WariationJTableListSelectionHandler());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		setLayout(new BoxLayout(this, BoxLayout.X_AXIS));

		wariationsTableJScrollPane = new javax.swing.JScrollPane();
		wariationsJTable = new javax.swing.JTable();

		wariationsJTable.setModel(new VariationsTableModel());
		wariationsTableJScrollPane.setViewportView(wariationsJTable);
		add(wariationsTableJScrollPane);
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Funkcja zwracaj�ca wybrane przez u�ytkownika wariacje. Wybrane przez
	 * u�ytkownika wariacje, to wariacje, dla kt�rych u�ytkownik ustawi� warto��
	 * wsp�czynnika wi�ksz� od zera.
	 * 
	 * @return Obiekt typu Vector<IVariation> zawieraj�cy wariacje wybrane przez
	 *         u�ytkownika
	 * @throws java.lang.Exception
	 */
	public Vector<IVariation> getWariations() {
		Vector<IVariation> wariations = new Vector<IVariation>();
		VariationsTableModel tableModel = (VariationsTableModel) wariationsJTable.getModel();
		IVariation temp;

		for (int i = 0; i < tableModel.getRowCount(); i++) {
			temp = (IVariation) tableModel.getWariation(i);
			if (temp.getCoefficient() != 0.0) {
				wariations.add(temp);
			}
		}

		return wariations;
	}

	/**
	 * Ustawia warto�ci w tabeli wed�ug zadanego wektora wariacji
	 * 
	 * @param wariations
	 *            obiekt typu Vector<IWariations> z wariacjami
	 */
	public void setWariations(Vector<IVariation> wariations) {
		((VariationsTableModel) wariationsJTable.getModel()).clearParameters();

		for (IVariation wariation : wariations) {
			wariationsJTable.getModel().setValueAt(wariation.getCoefficient().toString(),
					VariationsFactory.getWariationNumber(wariation.getWariationName()), 1);
			if (wariation.getParametersQuantity() > 0) {
				wariationsJTable.getModel().setValueAt(wariation.getParameters(),
						VariationsFactory.getWariationNumber(wariation.getWariationName()), 0);
			}
		}
	}

	private javax.swing.JTable wariationsJTable;
	private javax.swing.JScrollPane wariationsTableJScrollPane;

	// End of variables declaration//GEN-END:variables

	class WariationJTableListSelectionHandler implements ListSelectionListener {
		public void valueChanged(ListSelectionEvent e) {
		}
	}
}
